// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// SECURITY FIX: Removed hardcoded credentials - must use environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Garantir que a URL sempre tem o protocolo https://
let finalSupabaseUrl = SUPABASE_URL;
if (finalSupabaseUrl && !finalSupabaseUrl.startsWith('http://') && !finalSupabaseUrl.startsWith('https://')) {
  finalSupabaseUrl = `https://${finalSupabaseUrl}`;
}

if (!finalSupabaseUrl || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables');
  throw new Error('Missing Supabase configuration. Please check your environment variables.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(finalSupabaseUrl, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
