name: Keep Supabase Alive

on:
  schedule:
    # Executa a cada 6 horas (0 0,6,12,18 * * *)
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch: # Permite execução manual

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Alive
        run: |
          curl -X GET "https://io-santaluzia-f2gvp9ozj-roque-projects.vercel.app/api/keep-supabase-alive" \
            -H "Content-Type: application/json"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
